FROM docker.io/rustlang/rust:nightly-trixie

WORKDIR /app
RUN wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
RUN tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz
RUN cp cargo-binstall /usr/local/cargo/bin

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends clang

RUN apt-get install -y --no-install-recommends nodejs npm

RUN cargo binstall cargo-leptos -y

RUN rustup target add wasm32-unknown-unknown
